title: p3ntest1ng
description: Art칤culos sobre ciberseguridad, hacking 칠tico, resoluci칩n de CTFs, programaci칩n y mucho m치s.
author: WildZarek
bio: Ethical Hacker | Penetration Tester | CTF Player | Red Team 游댮 Atenea CCN-CERT / HackTheBox
avatar: /assets/images/about/avatar.png
email: 
url: wildzarek.github.io

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme

remote_theme: ngzhio/jekyll-theme-hamilton

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics:

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus: 

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec
  
# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: WildZarek
  card: summary
logo: /assets/images/about/avatar.png
social:
  name: WildZarek
  links:
    - https://twitter.com/WildZarek
    - https://github.com/WildZarek
    - https://app.hackthebox.com/profile/18979
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: es

location: M치laga, Espa침a
skin: midnight

subscribe: false
